version: "3.0"

services:
  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./app:/usr/share/nginx/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/logs/nginx:/var/log/nginx
  php:
    image: php:7.3-fpm
    restart: always
    volumes:
      - ./app:/usr/share/nginx/html
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  redis:
    image: redis
    restart: always
