version: "3.0"

services:
  web:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  redis:
    image: redis
    restart: always
